package ProyectoFinal;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class memorama extends javax.swing.JFrame {
    
    Boolean iniciado = false, vale = false;
    String jugadores = "";
    int casillas[][] = new int[1][21];
    String jugador[][] = new String[1][2];
    int priboton = 0, segBoton = 0, primero = 0,movJugUno = 0, movJugDos = 0, parJugUno = 0, parJugDos = 0;
    
    public memorama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        btnAcercaD = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        cmbBxNivel = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        rbDosJugadores = new javax.swing.JRadioButton();
        rbIndividual = new javax.swing.JRadioButton();
        txtFTiempo = new javax.swing.JTextField();
        lblTiempo = new javax.swing.JLabel();
        lblPares = new javax.swing.JLabel();
        txtFPares = new javax.swing.JTextField();
        lbMoviMientos = new javax.swing.JLabel();
        txtFMovimientos = new javax.swing.JTextField();
        lblJugador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Memorama");
        setResizable(false);

        jSeparator1.setBackground(new java.awt.Color(153, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAcercaD.setText("Acerca de");
        btnAcercaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDActionPerformed(evt);
            }
        });

        btn1.setText(" ");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText(" ");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText(" ");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setText(" ");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText(" ");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setText(" ");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setText(" ");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText(" ");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setText(" ");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn10.setText(" ");
        btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10ActionPerformed(evt);
            }
        });

        btn11.setText(" ");
        btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn11ActionPerformed(evt);
            }
        });

        btn12.setText(" ");
        btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn12ActionPerformed(evt);
            }
        });

        btn13.setText(" ");
        btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn13ActionPerformed(evt);
            }
        });

        btn14.setText(" ");
        btn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn14ActionPerformed(evt);
            }
        });

        btn15.setText(" ");
        btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15ActionPerformed(evt);
            }
        });

        btn16.setText(" ");
        btn16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn16ActionPerformed(evt);
            }
        });

        btn17.setText(" ");
        btn17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn17ActionPerformed(evt);
            }
        });

        btn18.setText(" ");
        btn18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn18ActionPerformed(evt);
            }
        });

        btn19.setText(" ");
        btn19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn19ActionPerformed(evt);
            }
        });

        btn20.setText(" ");
        btn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn20ActionPerformed(evt);
            }
        });

        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });

        cmbBxNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Facil", "Intermedio", "Dificil" }));

        jLabel1.setText("Nivel");

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDosJugadores);
        rbDosJugadores.setText("2 Jugadores");
        rbDosJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDosJugadoresActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbIndividual);
        rbIndividual.setText("Individual");
        rbIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIndividualActionPerformed(evt);
            }
        });

        txtFTiempo.setEditable(false);
        txtFTiempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFTiempo.setText("00:00:00");
        txtFTiempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFTiempoActionPerformed(evt);
            }
        });

        lblTiempo.setText("Tiempo");

        lblPares.setText("Pares");

        txtFPares.setEditable(false);
        txtFPares.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFPares.setText(" ");
        txtFPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFParesActionPerformed(evt);
            }
        });

        lbMoviMientos.setText("Movimientos");

        txtFMovimientos.setEditable(false);
        txtFMovimientos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFMovimientos.setText(" ");
        txtFMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFMovimientosActionPerformed(evt);
            }
        });

        lblJugador.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblJugador.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAcercaD)
                            .addComponent(btnInstrucciones)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblTiempo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbBxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rbIndividual)
                                .addComponent(rbDosJugadores)
                                .addComponent(txtFTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFPares, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbMoviMientos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblPares)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnAcercaD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInstrucciones)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnReiniciar)
                        .addGap(34, 34, 34)
                        .addComponent(rbIndividual)
                        .addGap(18, 18, 18)
                        .addComponent(rbDosJugadores)
                        .addGap(26, 26, 26)
                        .addComponent(lblTiempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPares)
                        .addGap(12, 12, 12)
                        .addComponent(txtFPares, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbMoviMientos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblJugador)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn20, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn18, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn17, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn19, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn15, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn14, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn16, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFTiempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFTiempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFTiempoActionPerformed

    private void txtFParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFParesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFParesActionPerformed

    private void txtFMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFMovimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFMovimientosActionPerformed

    private void btnAcercaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDActionPerformed
        JOptionPane.showMessageDialog(null, "App creada por Rafa Rosas","Acerca De",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAcercaDActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        String instrucciones = "1. Selecciona los jugadores.\n" +
            "2. Dale clic en el botón de \"Reiniciar\" para empezar o reiniciar el juego.\n" +
            "3. En la parte inferior derecha se indica que jugador sigue.\n" +
            "4. Dale clic en cualquier imagen de \"Pokémon Go\" para que se muestre el Pokémon.\n" +
            "5. Nuevamente dale clic en una imagen para voltear otra carta.\n" +
            "\t      5.1 Si son iguales, se le dará un punto al jugador y se colorea del color del jugador\n" +
            "\t\t         se quedarán descubiertas y el jugador tendrá otra oportunidad.\n" +
            "\t      5.2 Si son diferentes, se voltean las cartas y el sigue el otro jugador (paso 3).\n" +
            "6. Trata de Memorizar o recordar donde quedaron los Pokémon para poder lograr más puntos.\n" +
            "7. El jugador con más puntos ganara, en caso de empate al final serán notificados.\n" +
            "8. Diviértete es solo un juego. = )";
        
        JOptionPane.showMessageDialog(null, instrucciones,"Instrucciones",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
      int dialogButton = JOptionPane.YES_NO_OPTION;
        if (iniciado == true){
            int dialogResult = JOptionPane.showConfirmDialog (null, "Quieres reiniciar el juego?","Warning",dialogButton);
            if(dialogResult == JOptionPane.NO_OPTION){
                return;
            }
        }
        if (jugadores!="") {
            iniciado= true;
            CargarImagenesVolteadas();
            asignarImagenes();
            cambiarJugador();
            txtFPares.setText("0");
            txtFPares.setText("0");
            priboton = 0; segBoton = 0; primero = 0; movJugUno = 0; movJugDos = 0; parJugUno = 0; parJugDos = 0;
        }else{
            JOptionPane.showMessageDialog(null, "Selecciona cuantos jugadores!","Instrucciones",JOptionPane.CANCEL_OPTION);
            rbIndividual.requestFocus();
        }
    }//GEN-LAST:event_btnReiniciarActionPerformed

    private void asignarImagenes(){
        Random rand = new Random();
        int num = 0, c = 1, espacios = 0, cntVeces = 0;
        int sinAsigSegui = 0;
        boolean asignado= false;
        
        for (int i = 0; i < 21; i++) {
            casillas[0][i]=99;
        }
        while(espacios < 20){
            num = rand.nextInt(10);
            if (num != 0){
                cntVeces =  contarNumero(num);
                if (cntVeces <2){
                    while(!asignado){
                        if(casillas[0][c] == 99){
                            casillas[0][c] = num;
                            asignado= true;
                            espacios++;
                            sinAsigSegui = 0;
                        }
                        c++;
                    }
                }
            }
            asignado = false;
            sinAsigSegui++;
            if (sinAsigSegui>=6 && espacios > 15){
                for (int i = 1; i <= 10; i++) {
                    cntVeces =  contarNumero(i);
                    if (cntVeces<2) {
                        espacios++;
                        casillas[0][espacios] = i;
                    }
                }
            }
        }
    }
    
    private int contarNumero(int num){
        int veces = 0;
        for (int i = 0; i < 20; i++) {
            int valor = casillas[0][i];
            if (valor == num){
                veces++;
            }
        }
        return veces;
    }
    
    private void validarSiPar(int boton, int pokemon){
        if(priboton != boton){
            if (primero != 0){
                segBoton = boton;
                if (primero == pokemon) {
                    JOptionPane.showMessageDialog(null, "Si son Par","Urra",JOptionPane.INFORMATION_MESSAGE);
                    contarPares();
                    contarMovimientos();
                    marcarBotones(priboton, segBoton);
                }else{
                    JOptionPane.showMessageDialog(null, "No son iguales","Error",JOptionPane.CANCEL_OPTION);
                    voltearBoton("cara",priboton);
                    voltearBoton("cara",segBoton);
                    contarMovimientos();
                    cambiarJugador();
                }
                primero = 0;
                mostrarDatos();
            }else{
                primero = pokemon;
                priboton = boton;
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debes seleccionar otra carta!!","Error",JOptionPane.CANCEL_OPTION);
        }
    }
        
    private void cambiarJugador(){
        if (jugadores == "dos" || lblJugador.getText()==" ") {
            if (lblJugador.getText()=="Jugador 2" || lblJugador.getText()==" ") {
                lblJugador.setText("Jugador 1");
                lblJugador.setForeground(Color.red);
           }else if (lblJugador.getText()=="Jugador 1") {
                lblJugador.setText("Jugador 2");
                lblJugador.setForeground(Color.BLUE);
            }
        }
    }
    
    private void contarMovimientos(){
        if (lblJugador.getText()=="Jugador 1") {
            movJugUno++;
        }else if (lblJugador.getText()=="Jugador 2") {
            movJugDos++;
        }
    }
    
    private void contarPares(){
        if (lblJugador.getText()=="Jugador 1") {
            parJugUno++;
        }else if (lblJugador.getText()=="Jugador 2") {
            parJugDos++;
        }
        int total = parJugUno + parJugDos;
        if (total == 10){
            if (parJugUno > parJugDos){
                JOptionPane.showMessageDialog(null, "Jugador 1 =)","Ganador",JOptionPane.INFORMATION_MESSAGE);
            }else if (parJugUno < parJugDos){
                JOptionPane.showMessageDialog(null, "Jugador 2 =)","Ganador",JOptionPane.INFORMATION_MESSAGE);
            }else{
                 JOptionPane.showMessageDialog(null, "Empate =|","Empate",JOptionPane.INFORMATION_MESSAGE);
            }
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (null, "Quieres reiniciar el juego?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                iniciado= true;
                CargarImagenesVolteadas();
                asignarImagenes();
                lblJugador.setText(" ");
                cambiarJugador();
            }else{
               System.exit(0);
            }
        }
    }
    
    private void mostrarDatos(){
        if (lblJugador.getText()=="Jugador 1") {
            txtFMovimientos.setText(""+movJugUno);
            txtFPares.setText(""+parJugUno);
        }else if (lblJugador.getText()=="Jugador 2") {
            txtFMovimientos.setText(""+movJugDos);
            txtFPares.setText(""+parJugDos);
        }
    }
    
    private void marcarBotones(int uno, int dos){
        if (lblJugador.getText()=="Jugador 1") {
            voltearBoton("red", uno);
            voltearBoton("red", dos);
        }else if (lblJugador.getText()=="Jugador 2") {
            voltearBoton("blue", uno);
            voltearBoton("blue", dos);
        }
    }
    
    private void voltearBoton(String tipo, int boton){
        String path = "";
        if (tipo=="cara") {
            path = "Imagenes\\PoGo.PNG";
        }else if (tipo=="poke") {
            path = "Imagenes\\" + Integer.toString(casillas[0][boton]) + ".jpg";
        }else if (tipo=="red") {
            path = "Imagenes\\" + Integer.toString(casillas[0][boton]) + " red.jpg";
        }else if (tipo=="blue") {
            path = "Imagenes\\" + Integer.toString(casillas[0][boton]) + " blue.jpg";            
        }
        
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Icon fondo = new ImageIcon(icon.getImage().getScaledInstance(btn1.getWidth(), btn1.getHeight(), Image.SCALE_DEFAULT));        
        switch(boton){
            case 1:
                btn1.setIcon(fondo);
                break;
            case 2:
                btn2.setIcon(fondo);
                break;
            case 3:
                btn3.setIcon(fondo);
                break;
            case 4:
                btn4.setIcon(fondo);
                break;
            case 5:
                btn5.setIcon(fondo);
                break;
            case 6:
                btn6.setIcon(fondo);
                break;
            case 7:
                btn7.setIcon(fondo);
                break;
            case 8:
                btn8.setIcon(fondo);
                break;
            case 9:
                btn9.setIcon(fondo);
                break;
            case 10:
                btn10.setIcon(fondo);
                break;
            case 11:
                btn11.setIcon(fondo);
                break;
            case 12:
                btn12.setIcon(fondo);
                break;
            case 13:
                btn13.setIcon(fondo);
                break;
            case 14:
                btn14.setIcon(fondo);
                break;
            case 15:
                btn15.setIcon(fondo);
                break;
            case 16:
                btn16.setIcon(fondo);
                break;
            case 17:
                btn17.setIcon(fondo);
                break;
            case 18:
                btn18.setIcon(fondo);
                break;
            case 19:
                btn19.setIcon(fondo);
                break;
            case 20:
                btn20.setIcon(fondo);
                break;
        }
    }
    
    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        if(iniciado==true){
            int btn = 2;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        if(iniciado==true){
            int btn = 6;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        if(iniciado==true){
            int btn = 3;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        if(iniciado==true){
            int btn = 4;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if(iniciado==true){
            int btn = 1;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        if(iniciado==true){
            int btn = 5;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        if(iniciado==true){
            int btn = 7;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        if(iniciado==true){
            int btn = 8;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn11ActionPerformed
        if(iniciado==true){
            int btn = 11;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn11ActionPerformed

    private void btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn12ActionPerformed
       if(iniciado==true){
            int btn = 12;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn12ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        if(iniciado==true){
            int btn = 9;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10ActionPerformed
        if(iniciado==true){
            int btn = 10;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn10ActionPerformed

    private void btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn13ActionPerformed
        if(iniciado==true){
            int btn = 13;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn13ActionPerformed

    private void btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15ActionPerformed
        if(iniciado==true){
            int btn = 15;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn15ActionPerformed

    private void btn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn14ActionPerformed
        if(iniciado==true){
            int btn = 14;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn14ActionPerformed

    private void btn16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn16ActionPerformed
        if(iniciado==true){
            int btn = 16;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn16ActionPerformed

    private void btn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn20ActionPerformed
        if(iniciado==true){
            int btn = 20;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn20ActionPerformed

    private void btn18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn18ActionPerformed
        if(iniciado==true){
            int btn = 18;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn18ActionPerformed

    private void btn17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn17ActionPerformed
        if(iniciado==true){
            int btn = 17;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn17ActionPerformed

    private void btn19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn19ActionPerformed
        if(iniciado==true){
            int btn = 19;
            voltearBoton("poke", btn);
            validarSiPar(btn, casillas[0][btn]);
        }else{
            JOptionPane.showMessageDialog(null, "Dale clic en el boton de Reiniciar","Error",JOptionPane.CANCEL_OPTION);
            btnReiniciar.requestFocus();
        }
    }//GEN-LAST:event_btn19ActionPerformed

    private void rbIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIndividualActionPerformed
        jugadores = "uno";
        btnReiniciar.requestFocus();
    }//GEN-LAST:event_rbIndividualActionPerformed

    private void rbDosJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDosJugadoresActionPerformed
        jugadores = "dos";
        btnReiniciar.requestFocus();
    }//GEN-LAST:event_rbDosJugadoresActionPerformed

    private void CargarImagenesVolteadas(){
        for (int i = 1; i <= 20; i++) {
            voltearBoton("cara",i);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memorama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAcercaD;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbBxNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbMoviMientos;
    private javax.swing.JLabel lblJugador;
    private javax.swing.JLabel lblPares;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JRadioButton rbDosJugadores;
    private javax.swing.JRadioButton rbIndividual;
    private javax.swing.JTextField txtFMovimientos;
    private javax.swing.JTextField txtFPares;
    private javax.swing.JTextField txtFTiempo;
    // End of variables declaration//GEN-END:variables
}
